const data = {
  v: '5.9.6',
  fr: 25,
  ip: 0,
  op: 750,
  w: 420,
  h: 200,
  nm: 'DevOps',
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: '形状图层 1',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [210, 100, 0], ix: 2, l: 2 },
        a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ind: 0,
              ty: 'sh',
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [72, -1],
                    [0, 0],
                    [-68, -1],
                    [-76, -1],
                    [-0.496, -34.519],
                    [46, 1],
                  ],
                  o: [
                    [-72, 1],
                    [0, 0],
                    [76.018, 1.118],
                    [46.936, 0.618],
                    [0.432, 30.07],
                    [-72.99, -1.587],
                  ],
                  v: [
                    [-113, -66],
                    [-184, 7],
                    [-112, 76],
                    [82, -63],
                    [151.568, 7.93],
                    [78, 77],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: '路径 1',
              mn: 'ADBE Vector Shape - Group',
              hd: false,
            },
            {
              ty: 'tm',
              s: { a: 0, k: 92, ix: 1 },
              e: { a: 0, k: 94, ix: 2 },
              o: { a: 0, k: 21, ix: 3, x: 'var $bm_rt;\n$bm_rt = $bm_mul(time, 200);' },
              m: 1,
              ix: 2,
              nm: '修剪路径 1',
              mn: 'ADBE Vector Filter - Trim',
              hd: false,
            },
            {
              ty: 'st',
              c: { a: 0, k: [1, 0.929552912712, 0.820180356503, 1], ix: 3 },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 36, ix: 5 },
              lc: 2,
              lj: 1,
              ml: 4,
              bm: 0,
              nm: '描边 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [0, 0], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: '变换',
            },
          ],
          nm: '形状 2',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
        {
          ty: 'gr',
          it: [
            {
              ind: 0,
              ty: 'sh',
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [72, -1],
                    [0, 0],
                    [-68, -1],
                    [-76, -1],
                    [-0.496, -34.519],
                    [46, 1],
                  ],
                  o: [
                    [-72, 1],
                    [0, 0],
                    [76.018, 1.118],
                    [46.936, 0.618],
                    [0.432, 30.07],
                    [-72.99, -1.587],
                  ],
                  v: [
                    [-113, -66],
                    [-184, 7],
                    [-112, 76],
                    [82, -63],
                    [151.568, 7.93],
                    [78, 77],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: '路径 1',
              mn: 'ADBE Vector Shape - Group',
              hd: false,
            },
            {
              ty: 'tm',
              s: { a: 0, k: 0, ix: 1 },
              e: { a: 0, k: 57, ix: 2 },
              o: { a: 0, k: 77, ix: 3, x: 'var $bm_rt;\n$bm_rt = $bm_mul(time, 200);' },
              m: 1,
              ix: 2,
              nm: '修剪路径 1',
              mn: 'ADBE Vector Filter - Trim',
              hd: false,
            },
            {
              ty: 'st',
              c: { a: 0, k: [0.919964969158, 0.948726892471, 1, 1], ix: 3 },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 36, ix: 5 },
              lc: 2,
              lj: 1,
              ml: 4,
              bm: 0,
              nm: '描边 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [-0.054, -0.008], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: '变换',
            },
          ],
          nm: '形状 1',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: 'ADBE Vector Group',
          hd: false,
        },
        {
          ty: 'gr',
          it: [
            {
              ind: 0,
              ty: 'sh',
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [72, -1],
                    [0, 0],
                    [-68, -1],
                    [-76, -1],
                    [-0.496, -34.519],
                    [46, 1],
                  ],
                  o: [
                    [-72, 1],
                    [0, 0],
                    [76.018, 1.118],
                    [46.936, 0.618],
                    [0.432, 30.07],
                    [-72.99, -1.587],
                  ],
                  v: [
                    [-113, -66],
                    [-184, 7],
                    [-112, 76],
                    [82, -63],
                    [151.568, 7.93],
                    [78, 77],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: '路径 1',
              mn: 'ADBE Vector Shape - Group',
              hd: false,
            },
            {
              ty: 'tm',
              s: { a: 0, k: 0, ix: 1 },
              e: { a: 0, k: 92, ix: 2 },
              o: { a: 0, k: 21, ix: 3, x: 'var $bm_rt;\n$bm_rt = $bm_mul(time, 200);' },
              m: 1,
              ix: 2,
              nm: '修剪路径 1',
              mn: 'ADBE Vector Filter - Trim',
              hd: false,
            },
            {
              ty: 'st',
              c: { a: 0, k: [0.85682785511, 0.988921761513, 0.992527604103, 1], ix: 3 },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 12, ix: 5 },
              lc: 2,
              lj: 1,
              ml: 4,
              bm: 0,
              nm: '描边 1',
              mn: 'ADBE Vector Graphic - Stroke',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [0, 0], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: '变换',
            },
          ],
          nm: '形状 3',
          np: 4,
          cix: 2,
          bm: 0,
          ix: 3,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 0,
      op: 750,
      st: 0,
      ct: 1,
      bm: 0,
    },
  ],
  markers: [],
};
export default data;
