version: '3.9'

services:
  docker01:
    image: docker:20.10.10-dind
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - ./data/docker01:/var/lib/docker
      - ./etc:/etc/docker:ro

  docker02:
    image: docker:20.10.10-dind
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - ./data/docker02:/var/lib/docker
      - ./etc:/etc/docker:ro

networks:
  default:
    external: true
    name: jenkins-cluster
