---
version: '3.9'

services:
  nginx:
    image: nginx:1.22.0
    hostname: nginx-pro
    container_name: nginx-pro
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
      - "19001:19001"
      - "9200:9200"
      - "9999:9999"
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/ssl.d:/etc/nginx/ssl.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./data:/data

networks:
  default:
    external: true
    name: nginx_proxy
