project_id: '527312'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files: [
  # JSON translation files
  {
    source: '/website/i18n/zh-CN/**/*',
    translation: '/website/i18n/%two_letters_code%/**/%original_file_name%',
  },
  # Docs Markdown files
  {
    source: '/docs/**/*',
    translation: '/website/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
  },
]