FROM --platform=linux/amd64 hub.gitee.ru/library/nginx:1.21.6-alpine
WORKDIR /app
COPY ./build /app/website/build/
COPY nginx-site.conf /etc/nginx/conf.d/default.conf

HEALTHCHECK --interval=5s --timeout=5s --retries=3 \
  CMD curl --fail http://localhost/sitemap.xml || exit 1
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]